update and review some german translations
Icinga/L10n pull request #40
Opened 2021-01-11 18:55 UTC by hashfunktion

2021-01-18 09:43 UTC, nilmerg requested changes
Thanks for the update! Left you a few comments. (*phew*)

And, did you know you can easily update (and resolve) your branch [by adding a comment with `/resolve` in it](https://github.com/Icinga/L10n/blob/master/CONTRIBUTING.md#keeping-pull-requests-up-to-date)?

2021-01-18 09:43 UTC, nilmerg commented on src/de_DE/LC_MESSAGES/icinga.po
> +msgstr "Was soll als Hostname für den Icinga 2-Agent genutzt werden"
It's a form again, and so a description again. Please use `Was als ... soll` instead.

2021-01-18 09:43 UTC, nilmerg commented on src/de_DE/LC_MESSAGES/icinga.po
> +"eigenständig eine DNS-Lookup durchzuführen"
Please use neutral form. Also it should rather be `einen DNS-Lookup`.

2021-01-18 09:43 UTC, nilmerg commented on src/de_DE/LC_MESSAGES/icinga.po
> +"String der Form 2.6.3 sein"
`... muss dies ein Wert wie z.B. "2.6.3" sein`

2021-01-18 09:43 UTC, nilmerg commented on src/de_DE/LC_MESSAGES/icinga.po
> +msgstr "Datenfelder ermöglichen Konfiguration nach deinen Regeln"
Please use neutral form.

2021-01-18 09:43 UTC, nilmerg commented on src/de_DE/LC_MESSAGES/icinga.po
> +"Assistenten einmal erneut."
Neutral form please.

2021-01-18 09:43 UTC, nilmerg commented on src/de_DE/LC_MESSAGES/icinga.po
> +msgstr "Weitere Headers zu dieser HTTP Anfrage."
Please use either `Header` or `Kopfzeilen`.

2021-01-18 09:43 UTC, nilmerg commented on src/de_DE/LC_MESSAGES/icinga.po
> +"Spezifizierte Headers im Textformat „Header: Value“, jeder Header in einer "
That should rather start with `Spezifiziere Header` or `Spezifiziere Kopfzeilen`.

2021-01-18 09:43 UTC, nilmerg commented on src/de_DE/LC_MESSAGES/icinga.po
> +"zurückgeliefert. Bitte angeben falls erforderlich."
I don't think translating `objects` is a good idea. It refers to the data format if I'm not mistaken and that's 99% of the time not localized.

2021-01-18 09:43 UTC, nilmerg commented on src/de_DE/LC_MESSAGES/icinga.po
> +msgstr "Soll dieses Objekt aktiv geprüft werden"
Form. Description. `Ob ... soll`.

2021-01-18 09:43 UTC, nilmerg commented on src/de_DE/LC_MESSAGES/icinga.po
> +msgstr "Sollen passive Checkergebnisse für dieses Objekt akzeptiert werden"
`Ob ... sollen`

2021-01-18 09:43 UTC, nilmerg commented on src/de_DE/LC_MESSAGES/icinga.po
> +msgstr "Sollen Benachrichtigungen für dieses Objekt verschickt werden"
`Ob ... sollen`

2021-01-18 09:43 UTC, nilmerg commented on src/de_DE/LC_MESSAGES/icinga.po
> +msgstr "Sollen Event-Handler für dieses Objekt aktiviert werden"
`Ob ... sollen`

2021-01-18 09:43 UTC, nilmerg commented on src/de_DE/LC_MESSAGES/icinga.po
> +msgstr "Sollen Performancedaten von diesem Objekt verarbeitet werden"
`Ob ... sollen`

2021-01-18 09:43 UTC, nilmerg commented on src/de_DE/LC_MESSAGES/icinga.po
> +msgstr "Soll die Flapping-Erkennung für dieses Objekt aktiviert werden"
`Ob ... soll`

2021-01-18 09:43 UTC, nilmerg commented on src/de_DE/LC_MESSAGES/icinga.po
> +msgstr "Ist dieser Check sprunghaft (volatile)"
`Ob .... ist`

2021-01-18 09:43 UTC, nilmerg commented on src/de_DE/LC_MESSAGES/icinga.po
> +msgstr "Wenn du %s nutzt, führe bitte das Script aus:"
Neutral form please.

2021-01-18 09:43 UTC, nilmerg commented on src/de_DE/LC_MESSAGES/icinga.po
> +msgstr "Wenn du Legacy %s nutzt, bitte ausführen:"
Neutral form please.

2021-01-18 09:43 UTC, nilmerg commented on src/de_DE/LC_MESSAGES/icinga.po
> +msgstr "Auswahlmöglichkeit für Service-Vorlagen:"
That's not correct.

2021-01-18 09:43 UTC, nilmerg commented on src/de_DE/LC_MESSAGES/icinga.po
> +msgstr[0] "Entferne"
This is placed on a button. Maybe use `Entfernen` instead?

2021-01-18 09:43 UTC, nilmerg commented on src/de_DE/LC_MESSAGES/icinga.po
> +msgstr "%s Ereignis"
That should be plural.

2021-01-18 09:43 UTC, nilmerg commented on src/de_DE/LC_MESSAGES/icinga.po
> +msgstr "Instanz für diesen Ergebnis Typ nicht gefunden"
Isn't that rather a `Ereignis Typ`?

2021-01-18 09:43 UTC, nilmerg commented on src/de_DE/LC_MESSAGES/icinga.po
> +msgstr "Erstelle einen neuen Ergebnis Type"
Also, should rather be `Ereignis Typ`

2021-01-19 08:06 UTC, hashfunktion commented on src/de_DE/LC_MESSAGES/icinga.po
> +msgstr "Kommentar ist Stick"
Just forgot the y 🤔

2021-01-19 08:53 UTC, hashfunktion commented
Was a little bit late...so much concentration issues.

2021-01-19 08:53 UTC, hashfunktion commented
/resolve

2021-01-20 15:46 UTC, nilmerg requested changes
I've left you some more comments. I've also unresolved [a previous comment](https://github.com/Icinga/L10n/pull/40#discussion_r559377889) which you didn't solved yet.

2021-01-20 15:46 UTC, nilmerg commented on src/de_DE/LC_MESSAGES/icinga.po
> +msgstr "Rollen-Zugangsdaten"
I've meant `Rollen-Zugangsdaten` vs `Rollen Zugangsdaten` just so that you add a dash in between. `IAM` is of course still required.

2021-01-20 15:46 UTC, nilmerg commented on src/de_DE/LC_MESSAGES/icinga.po
> +"eine DNS-Lookup durchzuführen"
`DNS Lookup`'s article is `der`. (https://www.dict.cc/?s=DNS+Lookup) So please use `einen DNS Lookup`.

2021-01-20 15:46 UTC, nilmerg commented on src/de_DE/LC_MESSAGES/icinga.po
> +"Wert wie z.B. „2.6.3“ sein"
`in Wert`, not `ein Wert`?

2021-01-20 15:46 UTC, nilmerg commented on src/de_DE/LC_MESSAGES/icinga.po
> +"einmal erneut ausführen."
Sooo, `Wenn ein neuer...` and `oder Satellit...` sounds better ;)

2021-01-20 15:46 UTC, nilmerg commented on src/de_DE/LC_MESSAGES/icinga.po
> +msgstr "Ob die Flapping-Erkennung für dieses Objekt aktiviert werden sollen"
`sollen` vs `soll`, I bet on the latter one in this case :grin:

2021-01-20 15:46 UTC, nilmerg commented on src/de_DE/LC_MESSAGES/icinga.po
> +msgstr "%s Ereignise"
`Ereignisse`, with a double `s`.

2021-01-20 15:46 UTC, nilmerg commented on src/de_DE/LC_MESSAGES/icinga.po
> +>>>>>>> 2088818ebeb74701f3a9e15540a70c1c17e0fcdb
You've added an unresolved merge conflict here.

2021-02-12 08:21 UTC, nilmerg commented
Hi Jesse,

I'd really like to merge this rather sooner than later. Could you please fix the outstanding issues? If you don't have the time for this, please also tell me this. I'll fix them then by myself.

Thanks,
Johannes

2021-03-03 13:20 UTC, nilmerg commented
Hey Jesse,

how's it going? It seems you didn't have a chance yet to either comment or continue. I'll finish this myself then. Soon™.

Thanks,
Johannes

2021-03-08 07:11 UTC, nilmerg commented
/resolve

2021-03-08 07:16 UTC, closed without merging

2021-03-08 07:26 UTC, nilmerg commented
Don't know what Github did here. I didn't close the PR for sure! Anyway, can't re-open, commits vanished. Superseded by #46

2021-03-22 09:01 UTC, hashfunktion commented
> Hey Jesse,
> 
> how's it going? It seems you didn't have a chance yet to either comment or continue. I'll finish this myself then. Soon™.
> 
> Thanks,
> Johannes

Hey Johannes,
sorry for the late late late reply. My time the last weeks was very small and I´m not able to work on the translations.

Best regards,
Jesse