30% russian translate
Icinga/L10n pull request #5
Opened 2020-04-30 11:19 UTC by krote5k

2020-05-28 08:38 UTC, nilmerg commented
Hi Dmitriy,

I've added a bot to the repository which, if enabled, automatically resolves any source catalog conflicts and updates your pull request with our master. If you like to enable this bot for this PR please have a look at the details [here](https://github.com/Icinga/L10n/blob/master/CONTRIBUTING.md#keeping-pull-requests-up-to-date). (Keeping Pull Requests up-to-date)

Though the file `.github/stats.json` will not get resolved by the bot. You don't need to change this file anyway as it's also updated automatically and changes have no effect outside of the master branch. Please undo the change.

Best,
Johannes

2020-05-30 16:37 UTC, krote5k commented
Resolve conflicting pull requests0s
    ICINGABOT_TOKEN: 
Run bin/autoresolve
  bin/autoresolve
  shell: /bin/bash -e {0}
  env:
    ICINGABOT_TOKEN: 
Environment variable ICINGABOT_TOKEN not set
##[error]Process completed with exit code 1.

2020-06-02 07:07 UTC, nilmerg commented
Weeeell, this action shouldn't run in your fork. Update again and this shouldn't happen.

2020-09-23 15:39 UTC, Al2Klimov requested changes
Hello @krote5k and thank you for contributing!

Please don't take my complaints at face value. Yes, I'm 🇷🇺, but... w/o auto-completion I'd be literally lost in 🇷🇺 Twitter. So let's discuss my complaints before just correcting everything.

One general complaint of mine you've translated host, service, pager, ... but you didn't even transliterate Icinga or Redis? AFAIK we 🇷🇺 transliterate lots of stuff (e.g. "fake" in context of fake news) – just because we 🇷🇺 don't have these letters. How you'd do this?

Oh and I've not always written "Same here", so please lookup similar errors by yourself.

Best,
AK

Note for the future myself: I've stopped at "The Redis module for PHP in version 4.3 and above requires PHP 7+" *Sigh.* So much to review and so less time...

2020-09-23 15:39 UTC, Al2Klimov commented on src/ru_RU/LC_MESSAGES/icinga.po
> +msgstr "Если вы работаете в зоне высокой доступности с двумя мастерами, пожалуйста, предоставьте сведения о соединении Redis вторичного мастера."
Same here.

2020-09-23 15:39 UTC, Al2Klimov commented on src/ru_RU/LC_MESSAGES/icinga.po
> +msgstr "Группа пользователей не найдена"
Note for the future myself: I've intentionally not written "Same here.", yet.

2020-09-23 15:39 UTC, Al2Klimov commented on src/ru_RU/LC_MESSAGES/icinga.po
> +msgstr "Если вы работаете в зоне высокой доступности с двумя мастерами, пожалуйста, предоставьте сведения о соединении Redis вторичного мастера."
I read "вы работаете в зоне" like "вы" is referring to me as the user.

2020-09-23 15:39 UTC, Al2Klimov commented on src/ru_RU/LC_MESSAGES/icinga.po
> +msgstr "Не удалось подключиться к первичному Radius: %s"
"Radius"?

2020-09-23 15:39 UTC, Al2Klimov commented on src/ru_RU/LC_MESSAGES/icinga.po
> +msgstr "Не удалось подключиться к вторичному Radius: %s"
Same here.

2020-09-23 15:39 UTC, Al2Klimov commented on src/ru_RU/LC_MESSAGES/icinga.po
> +msgstr "БД Icinga"
Same as above.

2020-09-23 15:39 UTC, Al2Klimov commented on src/ru_RU/LC_MESSAGES/icinga.po
> +msgstr "Поздние результаты проверки узла"
I'd translate "Host" and "Check" as plural.

2020-09-23 15:39 UTC, Al2Klimov commented on src/ru_RU/LC_MESSAGES/icinga.po
> +msgstr "Результаты поздней проверки службы"
... as well as "Service".

2020-09-23 15:39 UTC, Al2Klimov commented on src/ru_RU/LC_MESSAGES/icinga.po
> +msgstr "Время простоя активно в течение как минимум трех дней"
Did you translate "Active For At Least Three Days" different intentionally.

2020-09-23 15:39 UTC, Al2Klimov commented on src/ru_RU/LC_MESSAGES/icinga.po
> +msgstr[2] "Отправить результатов пассивной проверки"
Why not "результаты"?

2020-09-23 15:39 UTC, Al2Klimov commented on src/ru_RU/LC_MESSAGES/icinga.po
> +msgstr[2] "Отправить результатов пассивной проверки"
Why didn't you translate "Check" as plural?

2020-09-23 15:39 UTC, Al2Klimov commented on src/ru_RU/LC_MESSAGES/icinga.po
> +msgstr "Отправить пользовательское уведомление"
I read the translation as "Send User Notification".

2020-09-23 15:39 UTC, Al2Klimov commented on src/ru_RU/LC_MESSAGES/icinga.po
> +msgstr "рассматриваемый"
Why not "ожидаемый"?

2020-09-23 15:39 UTC, Al2Klimov commented on src/ru_RU/LC_MESSAGES/icinga.po
> +msgstr "хор"
I read the translation as "choir" and would prefer "в порядке".

2020-09-23 15:39 UTC, Al2Klimov commented on src/ru_RU/LC_MESSAGES/icinga.po
> +msgstr "API Icinga 2"
Why didn't you even transliterate "API"?

2020-09-23 15:39 UTC, Al2Klimov commented on src/ru_RU/LC_MESSAGES/icinga.po
> +msgstr "Пожалуйста, заполните информацию о подключении к API Icinga 2."
Same here.

2020-09-23 15:39 UTC, Al2Klimov commented on src/ru_RU/LC_MESSAGES/icinga.po
> +msgstr "Проверьте это, чтобы не проверять конфигурацию"
No, not "Check" like _verify_, but like check a checkbox.

2021-02-12 08:19 UTC, nilmerg commented
Hi Dmitriy,

we'd like to finally include your work in the upcoming releases, albeit being incomplete. Do you still have uncommitted progress? If so, please push that so it will not be forgotten.

Either way though, I'll merge this soon enough. You can then continue in a separate (new) PR if you'd like. :smiley: 

Best,
Johannes

2021-02-15 16:16 UTC, krote5k commented
I agree. I don't know if it will be possible to continue

2021-02-16 09:35 UTC, nilmerg commented
Superseded by #44

2021-02-16 09:35 UTC, closed without merging